{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rundeckpro.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rundeckpro.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "rundeckpro.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
