# ACL Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.acl.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rundeckpro.labels" . | nindent 4 }}
type: Opaque
data:
  admin-role.aclpolicy: {{ .Values.aclFile | b64enc }}
---
# Kubeconfig Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kubeconfig.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rundeckpro.labels" . | nindent 4 }}
type: Opaque
data:
  config: {{ .Values.kubeconfig | b64enc }}
---
# realm.properties Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.realm.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rundeckpro.labels" . | nindent 4 }}
type: Opaque
data:
  realm.properties: {{ .Values.realm | b64enc }}
